<h1><?php echo $lang['title']; ?></h1>
<br />

<p>
<a href="<?php echo $GLOBALS['baseUrl'].'/'.$GLOBALS['modPath']; ?>"><?php echo $lang['link1']; ?></a>
</p>
<br />
<?php echo $lang['text1Access']; ?>
<br />
<?php echo $lang['text2Access']; ?>
<br />
<a href="<?php echo $GLOBALS['baseUrl'].'/'.$GLOBALS['modPath'].'/manage-access'; ?>"><?php echo $lang['link2']; ?></a>
<br />
<br />

<?php echo $form->get('begin'); ?>

<button id="btnShow" type="button">Show more columns</button> 
<button id="btnHide" type="button">Hide some columns</button> 
<br />
<br />
<?php if(count($modList)>0){ ?>
<b><?php echo $lang['tb1Title']; ?></b>
<table class="table">
	<tr>

	    <th><?php echo $lang['tb1ModTitle']; ?></th>
	    <th><?php echo $lang['tb1ModDesc']; ?></th>
	    <th><?php echo $lang['tb1ModClassName']; ?></th>
	    <th><?php echo $lang['tb1ModVersion']; ?></th>
	    <th><?php echo $lang['tb1ModTime']; ?></th>
	    <th><?php echo $lang['tb1ModDeveloper']; ?></th>
	    <th><?php echo $lang['tb1ModRequired']; ?></th>

	    <th>
<div class="cbh">
<input type="checkbox" name="modCb" />
</div>
	    </th>
	</tr>
	<?php
	 for($i=0;$i<count($modList);$i++){
//	 foreach ($modList as $row) :
	 ?>
		<tr>

			<td><?php echo $modList[$i]['title'];
			 ?></td>
			<td><?php echo $modList[$i]['description'];
			 ?></td>
			<td><?php echo $modList[$i]['name'];
			 ?></td>
			<td><?php echo $modList[$i]['version'];
			 ?></td>
			<td><?php echo date(($GLOBALS['dateFormat']." "."H:i"), $modList[$i]['time']);
			 ?></td>
			<td><?php echo $modList[$i]['developer'];
			 ?></td>
			<td><?php 
//			echo $modList[$i]['requiredModules'];
				if($modList[$i]['status']!="active"){
					echo "Required modules: ".$modList[$i]['requiredModules'];
					echo "<br />";
					echo "<div class=\"blue\">You need to install required module(s) first!</div>";
				}
			 ?></td>
			<td>
<div class="cb">
			<?php 

if($modList[$i]['status']=="active"){

//			echo $modCbTagList[$i];
//			echo $form->get('res');
//$form->get('end');
	if($modCbArray[$i]['status']=="")
		$form->formMap['modCb']['attributes']=array();
	else
		$form->formMap['modCb']['attributes']=array('checked' => "checked");
	//$form->formMap['modCb']['attributes']=array();
	//$form->formMap['modCb']['attributes']=array('checked' => "checked");

	$form->formMap['modCb']['value']=$modCbArray[$i]['id'];
	echo $form->get('modCb');

//$form->get('title');
}
			 ?>
</div>
			 </td>

		</tr>
	<?php 
}
//	endforeach;
	 ?>
</table>
<br />

<div class="form-field">
<?php echo $form->get('save'); ?>
</div>
<?php }else{ ?>
<b><?php echo $lang['text3NoUninsMod']; ?></b>
<br />
<?php } ?>
<br />

<?php echo $form->get('end'); ?>

<?php if(count($modPassiveList)>0){ ?>
<b><?php echo $lang['tb2Title']; ?></b>
<table class="table">
	<tr>
	    <th><?php echo $lang['tb1ModTitle']; ?></th>
	    <th><?php echo $lang['tb1ModDesc']; ?></th>
	    <th><?php echo $lang['tb1ModClassName']; ?></th>
	    <th><?php echo $lang['tb1ModVersion']; ?></th>
	    <th><?php echo $lang['tb1ModTime']; ?></th>
	    <th><?php echo $lang['tb1ModDeveloper']; ?></th>
	</tr>
	<?php for($i=0;$i<count($modPassiveList);$i++){ ?>
		<tr>
			<td><?php echo $modPassiveList[$i]['title'];
			 ?></td>
			<td><?php echo $modPassiveList[$i]['description'];
			 ?></td>
			<td><?php echo $modPassiveList[$i]['module_name'];
			 ?></td>
			<td><?php echo $modPassiveList[$i]['version'];
			 ?></td>
			<td><?php echo date(($GLOBALS['dateFormat']." "."H:i"), $modPassiveList[$i]['time']);
			 ?></td>
			<td><?php echo $modPassiveList[$i]['developer'];
			 ?></td>
		</tr>
	<?php } ?>
</table>
<?php
 }else{ ?>
<br />
<b><?php echo $lang['text4NoInsMod']; ?></b>
<?php } ?>
<br />

<script>
$(document).ready(function(){
 $(".cbh input:checkbox").click(function() {
            var checkedStatus = this.checked;
            $(".cb input:checkbox").each(function() {
                this.checked = checkedStatus;
            });
        });

});
</script>
