			<div class="colmask">
				<div class="col1">
					<?php /* Content column start */ ?>
					<?php if (isset($Region['title'])) : ?>
					<h1 class="title" id="page-title"><?php echo ($Region['title']); ?></h1>
					<?php endif; ?>

					<?php /* Content area */ ?>

					<?php if (isset($Region['messageArea'])) : ?>
					&nbsp;<br />
					<div class="message-area">
					<?php echo ($Region['messageArea']); ?>
					</div>
					<?php endif; ?>

					<div class="content-cell">
					<?php include $contentView; ?>
					</div>

				</div>
			<div class="col2">
				<?php /* Left sidebar column start */ ?>
				<?php if (isset($Region['menuArea'])) : ?>
				<div class="menu-area">
						<?php echo ($Region['menuArea']); ?>
				</div>
				<?php endif; ?>
				<?php if (isset($Region['bar1Area'])) : ?>
				<div class="bar">
						<?php echo ($Region['bar1Area']); ?>
				</div>
				<?php endif; ?>
				<?php if (isset($Region['bar2Area'])) : ?>
				<div class="bar">
						<?php echo ($Region['bar2Area']); ?>
				</div>
				<?php endif; ?>
			</div>
		</div>
