<h1><?php echo $lang['title']; ?></h1>
<br />

<p>
<a href="<?php echo $GLOBALS['baseUrl'].'/'.$GLOBALS['modPath'].'/'.'add-snippet/'.$id; ?>"><?php echo $lang['link1']; ?></a>
</p>
<br />

<?php if ($id>0){ ?>

<?php 

	echo $lang['label1']." ".$pageDetails['title'];
	echo "<br>";
	echo $lang['label2']." ".$pageDetails['alias'];
	echo "<br>";

	echo "\n";

?>
<br />
<?php if (count($snippetList)>0){ ?>

<table class="table">
	<tr>

	    <th><?php echo $lang['tb1SnCode']; ?></th>
	    <th><?php echo $lang['tb1SnContent']; ?></th>

	    <th>&nbsp;</th>
	</tr>
	<?php foreach ($snippetList as $row) : ?>
		<tr>

			<td><?php echo $row['uri'];
			 ?></td>
			<td><?php echo strip_tags(htmlspecialchars_decode($row['content']))." ...";
			 ?></td>

			<td>
				<a href="<?php echo $GLOBALS['baseUrl'].'/'.$GLOBALS['modPath'].'/'.'edit-snippet'.'/'.$row['id']; ?>"><?php echo $lang['link2']; ?></a>
				<a href="<?php echo $GLOBALS['baseUrl'].'/'.$GLOBALS['modPath'].'/'.'delete-snippet'.'/'.$row['id']; ?>"><?php echo $lang['link3']; ?></a>
			</td>
		</tr>
	<?php endforeach; ?>
</table>
<br />
<?php }else{ ?>
<?php 
echo $lang['message2'];
 ?>
<?php } ?>

<?php }else{ ?>
<?php 
echo $lang['message1'];
 ?>
<?php } ?>
