<?php
$title = 'Delete Alias';
?>

<h1><?php echo $title; ?></h1>
<br />
	<a href="<?php echo $GLOBALS['baseUrl'].'/'.$GLOBALS['modPath'].'/list-aliases'; ?>">Show list of aliases!</a>
<br />
<br />
<?php if($id>0){ ?>

<?php if($deleted){ ?>
<p>The Alias with following details was deleted<br />

    alias path: '<?php echo $alias->alias; ?>'<br />
    source path: '<?php echo $alias->source; ?>'<br />

</p>
<?php }else{ ?>
<p>Are you sure that you want to delete Alias, which<br />

    path is: '<?php echo $alias->alias; ?>'<br />
    source is: '<?php echo $alias->source; ?>'<br />

</p>
<br />
<form action="<?php echo $GLOBALS['curUrl']; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $id; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>
<?php } ?>
<?php }else{

		foreach ($messages as $message) {
			echo $message;
			echo "<br />";
		}

 }
 ?>
