<?php
$title = 'Delete TSV Set';

	$form->formMap['keyFields']['guide']="Enter database table column names, which are considered as identifying key columns to find entries, which will be deleted. Separate the field names either with tabs or with comma and space. E.g. \"module_name, uri, type, integer_value\".";
	$form->formMap['tableName']['guide']="Enter database table name without prefix, which entries will be deleted. E.g. \"core_misc_data\".";
	$form->formMap['tsvSet']['guide']="";


?>
<h1><?php echo $title; ?></h1>
<br />
<a href="<?php echo $GLOBALS['baseUrl'].'/'.$GLOBALS['modPath']; ?>">Language module main links</a>
<br />
<br />
By using this method, you can delete values from any Allmice CMS database table using as input a TSV (tab separated values) table, if following conditions are satisfied:   
<br />
* Database table must have an id field and one or more unique key fields.
<br />
<br />
Instructions to use this method:
<br />
Prepare SQL table as a TSV table (in a spreadsheet program, text editor or otherwise).
<br />
Copy TSV table to the corresponding (Input) form field.
<br />
Phrases which are existing in database according to the inserted details will be deleted.
<br />
<br />
This TSV format presumes, that columns are separated by tabs.
<br />
First line must be header line with table field names (except field id) according to the structure of table, where you wish to insert/update entries.
<br />
<br />

<?php echo $form->get('begin'); ?>
<?php echo $form->get('id'); ?>

<div class="form-field">
<?php echo $form->get('tsvSet'); ?>
</div>
	<div class="guide">
	<?php echo $form->getGuide('tsvSet'); ?>
	</div>

<div class="form-field">
<?php echo $form->get('tableName'); ?>
</div>
	<div class="guide">
	<?php echo $form->getGuide('tableName'); ?>
	</div>

<div class="form-field">
<?php echo $form->get('keyFields'); ?>
</div>
	<div class="guide">
	<?php echo $form->getGuide('keyFields'); ?>
	</div>

<br />

<div class="form-field">
<?php echo $form->get('submit1'); ?>
</div>

<?php echo $form->get('end'); ?>
