<?php
$lang['title']=$GLOBALS['modName'].' Module Events';
$lang['tb1ColName']='Event name';
$lang['tb1ColLink']='Event link';
 ?>

<h1><?php echo $lang['title']; ?></h1>
<br />

<table>
<tr>
	<th><?php echo $lang['tb1ColName']; ?></th>
	<th><?php echo $lang['tb1ColLink']; ?></th>
</tr>
<?php foreach ($eventSet as $row) : ?>
	<tr>
		<td>
			<?php echo $row['specific_name']; ?>
		</td>
		<td>
			<a href="<?php echo $GLOBALS['baseUrl'].$row['uri']; ?>" target="_blank"><?php echo $row['uri']; ?></a>
		</td>
	</tr>
<?php endforeach; ?>
</table>
