<h1><?php echo $lang['title']; ?></h1>
<br />
<div class="menu-content">
<ul class="menu menu-parent">
	<li class="menu-item"><a href="<?php echo $GLOBALS['baseUrl']; ?>/app"><?php echo $lang['linkApp']; ?></a>
	<ul class="menu menu-parent">
		<li class="menu-item"><a href="<?php echo $GLOBALS['baseUrl']; ?>/app/manage-access"><?php echo $lang['linkAccess']; ?></a></li>
		<li class="menu-item"><a href="<?php echo $GLOBALS['baseUrl']; ?>/app/install-modules"><?php echo $lang['linkIns']; ?></a></li>
		<li class="menu-item"><a href="<?php echo $GLOBALS['baseUrl']; ?>/app/uninstall-modules"><?php echo $lang['linkUnins']; ?></a></li>
	</ul>
	</li>
</ul>
</div>
