<?php if($search->searchType>0 && $accessRight>0){ ?>
<?php
$title = $typeData['title'];

?>

<h1><?php echo $title; ?></h1>
<br />
<?php echo $typeData['description']; ?>

<?php echo $form->get('begin'); ?>
<div class="form-field">
<?php echo $form->get('id'); ?>
</div>
<div class="form-field">
<label><span class="label-text"><?php echo $form->getLabel('searchPhrase'); ?></span></label>
<?php echo $form->get('searchPhrase'); ?>
</div>
	<div class="guide">
	<?php echo $form->getGuide('searchPhrase'); ?>
	</div>

<div class="form-field">
<?php echo $form->get('search'); ?>
</div>

	<br />

<?php if (count($resultList)>0){ ?>
<hr />
<br />
<div class="form-field">
<?php echo $paginator->formWidget; ?>
</div>

<?php 
$mes1=str_replace("[noOfAllItems]",$paginator->noOfAllItems,$lang['message1']);
echo $mes1;
 ?>
	<br />
<?php 
if($paginator->formWidget!=""){
	$mes2=str_replace("[curPage]",($paginator->currentPage+1),$lang['message2']);
	$mes2=str_replace("[allPages]",($paginator->lastPage+1),$mes2);

	echo $mes2;

	echo "<br />\n";
}

	echo "<br />\n";
	echo $lang['tb1Title'];
	echo "<br />\n";
	echo "\n";

if($configData['searchResult']['listMode']=="table"){
 ?>
		<div style="width:100%">

		<table class="table">
		<tr>
<?php
for($i=0;$i<count($fieldTitles);$i++){

	if($fieldTitles[$i]!="[skip]"){
		echo "<th>".$fieldTitles[$i]."</th>\n";
	}
}

 ?>

		    <th>&nbsp;</th>
		</tr>

		<?php foreach ($resultList as $row) : ?>

<?php if(count($row)>0){ ?>
			<tr>

<?php
for($i=0;$i<count($fieldTitles);$i++){
	if($fieldTitles[$i]!="[skip]"){

		echo "<td>".$row[($fieldList[$i])]."</td>\n";
	}
}

 ?>
			    <td>
			        <a href="<?php 
						if($row['alias']=="")
							echo $GLOBALS['baseUrl'].$search->uri."/".$row['id'];
						else
							echo $GLOBALS['baseUrl'].$row['alias'];
			            ?>" target="_blank"><?php echo $lang['link1']; ?></a>

			    </td>

			</tr>
<?php }else{ ?>
			<tr>
			    <td>
					<?php echo $lang['noAccess']; ?>
			    </td>
			    <td>
					&nbsp;
			    </td>
			    <td>
					&nbsp;
			    </td>
			</tr>
<?php } ?>

			<?php endforeach; ?>
			</table>
			</div>

		<?php 
//End of case mode==table
}else{

	echo "<hr />\n";
	foreach ($resultList as $row) :

		if(count($row)>0){

			for($i=0;$i<count($fieldTitles);$i++){
				if($fieldTitles[$i]!="[skip]"){
					echo "<b>".$fieldTitles[$i]."</b>".": ";
					echo $row[($fieldList[$i])]."<br />\n";
				}

			}
 ?>
			        <div class="list-link"><?php echo "<b>".$lang['link1label']."</b>"; ?>: <a href="<?php 
						if($row['alias']=="")
							echo $GLOBALS['baseUrl'].$search->uri."/".$row['id'];
						else
							echo $GLOBALS['baseUrl'].$row['alias'];
			            ?>" target="_blank"><?php echo $lang['link1text']; ?></a></div>
<?php
					echo "<hr />\n";
//				echo "<br />\n";
		
		}

 	endforeach;


}
 ?>
		<?php 



		}else{
			echo "<br />";
			echo $lang['message3'];

		}
		 ?>

<?php echo $form->get('end'); ?>

<?php 
		}else{
			echo $lang['message4'];
		}

 ?>
