<!DOCTYPE html>
<html lang="<?php echo $GLOBALS['langCode2']; ?>" dir="<?php echo $GLOBALS['langDirection']; ?>">
<head>
<?php

$GLOBALS['layoutType']="leftBar";
//$GLOBALS['layoutType']="noBars";

$isMobile = (bool)preg_match('#\b(ip(hone|od)|android\b.+\bmobile|opera m(ob|in)i|windows (phone|ce)|blackberry'.
                    '|s(ymbian|eries60|amsung)|p(alm|rofile/midp|laystation portable)|nokia|fennec|htc[\-_]'.
                    '|up\.browser|[1-4][0-9]{2}x[1-4][0-9]{2})\b#i', $_SERVER['HTTP_USER_AGENT'] );

$menuStyleFile="all-menu-types.css";
$cssPath=$layoutPath."css/";

//$isMobile=true;
if($isMobile){
	$fileSysAbsPath=$_SERVER["DOCUMENT_ROOT"].$GLOBALS['pathData']['base'];
	$layoutHtmlFile=$fileSysAbsPath."/themes/ClassicBase/layout-mobile.phtml";
	$mobileStylePath=$GLOBALS['baseUrl']."/themes/ClassicBase/versions/teal/mobile-styles.css";
	$mainStylePath=$mobileStylePath;
	$layoutHeader=$fileSysAbsPath."/themes/ClassicBase/layout-mobile-header.phtml";
}
else{

	$fileSysAbsPath=$_SERVER["DOCUMENT_ROOT"].$GLOBALS['pathData']['base'];
	$layoutHtmlFile=$fileSysAbsPath."/themes/ClassicBase/versions/left-bar/layout-leftBar.phtml";
	$layoutStylePath=$GLOBALS['baseUrl']."/themes/ClassicBase/versions/teal/layout-leftBar.css";
	$mainStylePath=$GLOBALS['baseUrl']."/themes/ClassicBase/versions/teal/main-styles.css";
	$layoutHeader=$fileSysAbsPath."/themes/ClassicBase/layout-main-header.phtml";
}
 ?>

<title><?php 
if(isset($GLOBALS['titleTag'])){
	echo $GLOBALS['titleTag'];
}
 ?>
</title>

<?php 
if(isset($GLOBALS['metaTags']))
	echo $GLOBALS['metaTags']; 
 ?>

<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="<?php echo $layoutStylePath; ?>" media="screen" rel="stylesheet" type="text/css">
<link href="<?php echo $mainStylePath; ?>" media="screen" rel="stylesheet" type="text/css">
<?php 
if(isset($GLOBALS['headTags']))
	echo $GLOBALS['headTags']; 
 ?>
<?php if(isset($GLOBALS['faviconPath'])){ ?>
<link rel="shortcut icon" href="<?php echo $GLOBALS['faviconPath']; ?>">
<?php }
elseif(isset($GLOBALS['faviconImage'])){ ?>
<?php echo $GLOBALS['faviconImage']; ?>
<?php } ?>
</head>

<body>
<?php 
if(isset($GLOBALS['otherTags1']))
	echo $GLOBALS['otherTags1'];
 ?>

<?php 
	include ($layoutHeader);
 ?>

<?php 
	include ($layoutHtmlFile);
 ?>

<?php 
if (isset($Region['consentArea']) && $Region['consentArea']!="") : ?>

<div class="gap">
</div>
<div class="footer-area-set">
	<?php if (isset($Region['footerArea'])) : ?>
	<div class="footer-area">
      <div class="footer-cell">
        <?php echo ($Region['footerArea']); ?>
      </div>
	</div>
	<?php endif; ?>
	<div class="consent-area">
        <?php echo ($Region['consentArea']); ?>
	</div>
</div>
<?php else: ?>
	<div class="footer-area">
      <div class="footer-cell">
        <?php echo ($Region['footerArea']); ?>
      </div>
	</div>
<?php endif; ?>

<?php 
if(isset($GLOBALS['otherTags2']))
	echo $GLOBALS['otherTags2']; 
 ?>

</body>
</html>
