<h1><?php echo $lang['title']; ?></h1>
<div class="link">
	<a href="<?php echo $GLOBALS['baseUrl'].'/'.$GLOBALS['modPath'].'/list-all-postal-addresses'; ?>"><?php echo $lang['link1']; ?></a>
</div>
<br />

<?php echo $form->get('begin'); ?>
<div class="form-field">
<?php echo $form->get('userId'); ?>
</div>
	<div class="guide">
	<?php echo $form->getGuide('userId'); ?>
	</div>

<?php 
$visibleFields=$form->visibleFields;
for($i=0;$i<count($visibleFields);$i++){
 ?>

<div class="form-field">
	<?php echo $form->get($visibleFields[$i]['fieldName']); ?>
</div>
	<div class="guide">
	<?php echo $form->getGuide($visibleFields[$i]['fieldName']); ?>
	</div>

<?php
}
 ?>
<div class="form-field">
	<?php echo $form->get('save'); ?>
</div>
<?php echo $form->get('end'); ?>
