<?php 
$messages=array();
if($id<=0){
	$messages[]=$lang['message1'];
}
if(!$ownEntry){
	$messages[]=$lang['message2'];
}
switch($form->formMap['status']['value']){
	case "verified":
	$statusLabel=$lang['statusOption1'];
	break;
	case "created":
	$statusLabel=$lang['statusOption0'];
	break;
	case "created-recent":
	$statusLabel=$lang['statusOption2'];
	break;
	default:
	$statusLabel="";
}

 ?>

<h1><?php echo $lang['title']; ?></h1>
<div class="link">
	<a href="<?php echo $GLOBALS['baseUrl'].'/'.$GLOBALS['modPath'].'/list-email-addresses'; ?>"><?php echo $lang['link1']; ?></a>
</div>
<br />

<?php if(count($messages)==0){ ?>

<?php echo $form->get('begin'); ?>
<?php echo $form->get('id'); ?>

<div class="form-field">
<?php echo $form->formMap['emailAddress']['label']." ".$form->formMap['emailAddress']['value']; ?>
</div>
<div class="form-field">
<?php echo $form->formMap['status']['label']." ".$statusLabel; ?>
</div>
<br />
<div class="form-field">
<?php echo $form->get('memWordQuestion'); ?>
</div>
	<div class="guide">
	<?php echo $form->getGuide('memWordQuestion'); ?>
	</div>
<div class="form-field">
<?php echo $form->get('memWord'); ?>
</div>
	<div class="guide">
	<?php echo $form->getGuide('memWord'); ?>
	</div>
<div class="form-field">
<?php echo $form->get('comment'); ?>
</div>
	<div class="guide">
	<?php echo $form->getGuide('comment'); ?>
	</div>
<div class="form-field">
<?php echo $form->get('save'); ?>
</div>
<?php echo $form->get('end'); ?>

<?php
}else{
	foreach ($messages as $message) {
		echo $message;
		echo "<br />";
	}
}
 ?>
