<!DOCTYPE html>
<html lang="<?php echo $GLOBALS['langCode']; ?>" dir="<?php echo $GLOBALS['langDirection']; ?>">
<head>

<?php

$GLOBALS['layoutType']="leftBar";
//$GLOBALS['layoutType']="noBars";

$isMobile = (bool)preg_match('#\b(ip(hone|od)|android\b.+\bmobile|opera m(ob|in)i|windows (phone|ce)|blackberry'.
                    '|s(ymbian|eries60|amsung)|p(alm|rofile/midp|laystation portable)|nokia|fennec|htc[\-_]'.
                    '|up\.browser|[1-4][0-9]{2}x[1-4][0-9]{2})\b#i', $_SERVER['HTTP_USER_AGENT'] );

$menuStyleFile="all-menu-types.css";
$cssPath=$layoutPath."css/";
//$isMobile=true;
$fileSysAbsPath=$_SERVER["DOCUMENT_ROOT"].$GLOBALS['pathData']['base'];
if($isMobile){
	$layoutMiddleArea=$fileSysAbsPath."/core/themes/AllmiceDefault/layout-mobile.phtml";
	$layoutHeader=$fileSysAbsPath."/core/themes/AllmiceDefault/layout-mobile-header.phtml";
	$mainStylePath=$GLOBALS['baseUrl']."/core/themes/AllmiceDefault/css/main-styles.css";
	$layoutStylePath=$GLOBALS['baseUrl']."/core/themes/AllmiceDefault/css/layout-mobile.css";
	$mobileStylePath=$GLOBALS['baseUrl']."/core/themes/AllmiceDefault/css/mobile-styles.css";
}
else{
	$layoutMiddleArea=$fileSysAbsPath."/core/themes/AllmiceDefault/layout-leftBar.phtml";
	$layoutHeader=$fileSysAbsPath."/core/themes/AllmiceDefault/layout-main-header.phtml";
	if (isset($Region['menuArea']) && $Region['menuArea']!="" || isset($Region['bar1Area']) && $Region['bar1Area']!="" || isset($Region['bar2Area']) && $Region['bar2Area']!=""){
		$layoutStylePath=$GLOBALS['baseUrl']."/core/themes/AllmiceDefault/css/layout-leftBar.css";
	}else{
		$layoutStylePath=$GLOBALS['baseUrl']."/core/themes/AllmiceDefault/css/layout-noBars.css";
	}
	$mainStylePath=$GLOBALS['baseUrl']."/core/themes/AllmiceDefault/css/main-styles.css";
}
 ?>

<title><?php 
if(isset($GLOBALS['titleTag'])){
	echo $GLOBALS['titleTag'];
}
 ?>
</title>

<?php 
if(isset($GLOBALS['metaTags']))
	echo $GLOBALS['metaTags']; 
 ?>

<meta name="viewport" content="width=device-width, initial-scale=1.0">
<?php if(isset($layoutStylePath) && $layoutStylePath!=""){ ?>
<link href="<?php echo $layoutStylePath; ?>" media="screen" rel="stylesheet" type="text/css">
<?php } ?>
<link href="<?php echo $mainStylePath; ?>" media="screen" rel="stylesheet" type="text/css">
<?php if(isset($mobileStylePath) && $mobileStylePath!=""){ ?>
<link href="<?php echo $mobileStylePath; ?>" media="screen" rel="stylesheet" type="text/css">
<?php } ?>

<?php 
if(isset($GLOBALS['scriptTags']))
	echo $GLOBALS['scriptTags']; 

if(isset($GLOBALS['headTags']))
	echo $GLOBALS['headTags']; 
 ?>
<?php if(isset($GLOBALS['faviconPath'])){ ?>
<link rel="shortcut icon" href="<?php echo $GLOBALS['faviconPath']; ?>">
<?php }
elseif(isset($GLOBALS['faviconImage'])){ ?>
<?php echo $GLOBALS['faviconImage']; ?>
<?php } ?>

</head>

<body>
<?php 
if(isset($GLOBALS['otherTags1']))
	echo $GLOBALS['otherTags1']; 

 ?>

<?php 
	include ($layoutHeader);
 ?>

<div class="middle-area">
<?php 
	include ($layoutMiddleArea);
 ?>
</div>

<?php 
if (isset($Region['consentArea']) && $Region['consentArea']!="") : ?>

<div class="gap">
</div>
<div class="footer-area-set">
	<?php if (isset($Region['footerArea'])) : ?>
	<div class="footer-area">
      <div class="footer-cell">
        <?php echo ($Region['footerArea']); ?>
      </div>
	</div>
	<?php endif; ?>
	<div class="consent-area">
        <?php echo ($Region['consentArea']); ?>
	</div>
</div>
<?php else: ?>
	<div class="footer-area">
      <div class="footer-cell">
		<?php if (isset($Region['footerArea'])) : ?>
        <?php echo ($Region['footerArea']); ?>
		<?php else: ?>
			<a href="http://www.allmice.com/cms" target="_blank">Allmice CMS</a><?php echo " 🐭 ".$GLOBALS['version']; ?>
		<?php endif; ?>
      </div>
	</div>
<?php endif; ?>

<?php 
if(isset($GLOBALS['otherTags2']))
	echo $GLOBALS['otherTags2']; 
 ?>
</body>
</html>
