<?php 
$messages=array();

if($id<=1){
	$messages[]=$lang['message1'];
}
 ?>
<h1><?php echo $lang['title']; ?></h1>
<div class="link">
    <a href="<?php echo $GLOBALS['baseUrl']."/".$GLOBALS['modPath']."/list-accounts"; ?>"><?php echo $lang['link1']; ?></a>
</div>
<br />
<?php 

if(count($messages)==0){
	if($deleted){
 ?>
<p><?php echo $lang['afterMessage']; ?><br />
    <?php echo $lang['afterField1']; ?>: '<?php echo $user->username; ?>'<br />
    <?php echo $lang['afterField2']; ?>: '<?php echo $user->mainEmail; ?>'<br />
</p>
<?php }else{ ?>

<?php echo $form->get('begin'); ?>
<?php echo $form->get('id'); ?>

<div class="form-field">
<?php echo $form->get('delMethod'); ?>
</div>
	<div class="guide">
	<?php echo $form->getGuide('delMethod'); ?>
	</div>

<br />
<p><?php echo $lang['beforeMessage']; ?><br />
    <?php echo $lang['beforeField1']; ?>: '<?php echo $user->username; ?>'<br />
    <?php echo $lang['beforeField2']; ?>: '<?php echo $user->mainEmail; ?>'<br />
</p>

<br />

<div>
    <input type="submit" name="del" value="<?php echo $lang['submitYes']; ?>" />
</div>

<?php echo $form->get('end'); ?>

<?php
	}
}else{
	foreach ($messages as $message) {
		echo $message;
		echo "<br />";
	}
}
 ?>
