<?php 
$messages=array();
if($id<=0){
	$messages[]=$lang['message1'];
}
if($hasContactForms){
	$messages[]=$lang['message3'];
}
if($isMainEmail){
	$messages[]=$lang['message4'];
}
 ?>
<h1><?php echo $lang['title']; ?></h1>
<div class="link">
    <a href="<?php echo $GLOBALS['baseUrl']."/".$GLOBALS['modPath']; ?>/list-all-email-addresses"><?php echo $lang['link1']; ?></a>
</div>
<br />

<?php if(count($messages)==0){ ?>
<?php if($deleted){ ?>
<p><?php echo $lang['afterMessage']; ?><br />
    <?php echo $lang['afterField1']; ?>: '<?php echo $email->username; ?>'<br />
    <?php echo $lang['afterField2']; ?>: '<?php echo $email->emailAddress; ?>'<br />
</p>
<?php }else{ ?>
<p><?php echo $lang['beforeMessage']; ?><br />
    <?php echo $lang['beforeField1']; ?>: '<?php echo $email->username; ?>'<br />
    <?php echo $lang['beforeField2']; ?>: '<?php echo $email->emailAddress; ?>'<br />
</p>

<br />
<form action="<?php echo $GLOBALS['curUrl']; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $item->id; ?>" />
    <input type="submit" name="del" value="<?php echo $lang['submitYes']; ?>" />
</div>
</form>
<?php
	}
}else{
	foreach ($messages as $message) {
		echo $message;
		echo "<br />";
	}
}
 ?>
