<?php 
$messages=array();
if($id<1){
	$messages[]=$lang['message1'];
}
if(!$ownEntry){
	$messages[]=$lang['message2'];
}
if($id==1){
	$messages[]=$lang['message3'];
}
 ?>
<h1><?php echo $lang['title']; ?></h1>
<br />
<?php 
if(count($messages)==0){

	if($deleted){
 ?>
<?php }else{ ?>

<p><?php echo $lang['beforeMessage']; ?><br />
    <?php echo $lang['beforeField1']; ?>: '<?php echo $user->username; ?>'<br />
    <?php echo $lang['beforeField2']; ?>: '<?php echo $user->mainEmail; ?>'<br />
</p>

<br />
<?php echo $form->get('begin'); ?>
<div>
    <input type="hidden" name="id" value="<?php echo (int) $item->id; ?>" />
    <input type="submit" name="del" value="<?php echo $lang['submitYes']; ?>" />
</div>
<?php echo $form->get('end'); ?>

<?php
	}

}else{
	foreach ($messages as $message) {
		echo $message;
		echo "<br />";
	}
}
 ?>
