<?php
$title = 'Delete a Configuration Item';
?>

<h1><?php echo $title; ?></h1>
<br />
	<a href="<?php echo $GLOBALS['baseUrl'].'/'.$GLOBALS['modPath'].'/list-config'; ?>">Show list of configuration items!</a>
<br />
<br />

<?php if($id>0){ ?>
<?php if($deleted){ ?>
<p>The configuration item with following details was deleted<br />

    module name: '<?php echo $item->modName; ?>'<br />
    identifier (uri): '<?php echo $item->uri; ?>'<br />
    type: '<?php echo $item->type; ?>'<br />

</p>
<?php }else{ ?>
<p>Are you sure, that you want to delete configuration item, which details are<br />

    module name: '<?php echo $item->modName; ?>'<br />
    identifier (uri): '<?php echo $item->uri; ?>'<br />
    type: '<?php echo $item->type; ?>'<br />

</p>
<br />
<form action="<?php echo $GLOBALS['curUrl']; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $id; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>
<?php } ?>

<?php }else{
		foreach ($messages as $message) {
			echo $message;
			echo "<br />";
		}
 } ?>
