<?php
$title = 'Delete User';
?>
<h1><?php echo $title; ?></h1>
<br />
	<a href="<?php echo $GLOBALS['baseUrl'].'/'.$GLOBALS['modPath'].'/list-users'; ?>">Show list of users!</a>
<br />
<br />
<?php if($id>0){ ?>
<?php if($deleted){ ?>
<p>The User with following details was deleted<br />

    username: '<?php echo $item->username; ?>'<br />
    eMail: '<?php echo $item->eMail; ?>'<br />

</p>
<?php }else{ ?>
<p>Are you sure that you want to delete User, which<br />

    username is: '<?php echo $item->username; ?>'<br />
    eMail is: '<?php echo $item->eMail; ?>'<br />

</p>
<br />
<form action="<?php echo $GLOBALS['curUrl']; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $id; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>
<?php } ?>
<?php }else{
		foreach ($messages as $message) {
			echo $message;
			echo "<br />";
		}
 } ?>
