<?php
$title = 'Edit an Existing Alias';
?>

<h1><?php echo $title; ?></h1>
<br />
	<a href="<?php echo $GLOBALS['baseUrl'].'/'.$GLOBALS['modPath'].'/list-aliases'; ?>">Show list of aliases!</a>
<br />
<br />

<?php if($id>0){ ?>

<?php echo $form->get('begin'); ?>
<?php echo $form->get('id'); ?>

<div class="element">
<?php echo $form->get('alias'); ?>
</div>
<div class="element">
<?php 
 echo $form->get('source'); 
 ?>
</div>
<div class="element">
<?php echo $form->get('sourceStatus'); ?>
</div>
<div class="element">
<?php echo $form->get('save'); ?>
</div>

<?php echo $form->get('end'); ?>
<?php
 }else{

		foreach ($messages as $message) {
			echo $message;
			echo "<br />";
		}

 }
  ?>
